### ISSUE TITLE
How do I configure this?

### ISSUE THREAD

**Issue by R5fan** [mendel129/Unofficial-recycleapp.be-HASS#1]
Not sure this still works or is maintained, but if so, how do I configure it ? It needs my address somehow surely?

**Comment by mendel129** [comment]
It still works :-) Address is hardcoded on line 122.

recycleapp/igean functionality also became part of the better extensions https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer and https://github.com/mampfes/hacs_waste_collection_schedule, so I would suggest using those for a better overall experience ;-)

**Comment by R5fan** [comment]
thanks!
